<?php
$countries = array(
	'US' => __( 'United States (US)', 'wp-easycart' ),
	'CA' => __( 'Canada', 'wp-easycart' ),
	'GB' => __( 'United Kingdom (UK)', 'wp-easycart' ),
	'AU' => __( 'Australia', 'wp-easycart' ),
	'AF' => __( 'Afghanistan', 'wp-easycart' ),
	'AX' => __( '&#197;land Islands', 'wp-easycart' ),
	'AL' => __( 'Albania', 'wp-easycart' ),
	'DZ' => __( 'Algeria', 'wp-easycart' ),
	'AS' => __( 'American Samoa', 'wp-easycart' ),
	'AD' => __( 'Andorra', 'wp-easycart' ),
	'AO' => __( 'Angola', 'wp-easycart' ),
	'AI' => __( 'Anguilla', 'wp-easycart' ),
	'AQ' => __( 'Antarctica', 'wp-easycart' ),
	'AG' => __( 'Antigua and Barbuda', 'wp-easycart' ),
	'AR' => __( 'Argentina', 'wp-easycart' ),
	'AM' => __( 'Armenia', 'wp-easycart' ),
	'AW' => __( 'Aruba', 'wp-easycart' ),
	'AU' => __( 'Australia', 'wp-easycart' ),
	'AT' => __( 'Austria', 'wp-easycart' ),
	'AZ' => __( 'Azerbaijan', 'wp-easycart' ),
	'BS' => __( 'Bahamas', 'wp-easycart' ),
	'BH' => __( 'Bahrain', 'wp-easycart' ),
	'BD' => __( 'Bangladesh', 'wp-easycart' ),
	'BB' => __( 'Barbados', 'wp-easycart' ),
	'BY' => __( 'Belarus', 'wp-easycart' ),
	'BE' => __( 'Belgium', 'wp-easycart' ),
	'PW' => __( 'Belau', 'wp-easycart' ),
	'BZ' => __( 'Belize', 'wp-easycart' ),
	'BJ' => __( 'Benin', 'wp-easycart' ),
	'BM' => __( 'Bermuda', 'wp-easycart' ),
	'BT' => __( 'Bhutan', 'wp-easycart' ),
	'BO' => __( 'Bolivia', 'wp-easycart' ),
	'BQ' => __( 'Bonaire, Saint Eustatius and Saba', 'wp-easycart' ),
	'BA' => __( 'Bosnia and Herzegovina', 'wp-easycart' ),
	'BW' => __( 'Botswana', 'wp-easycart' ),
	'BV' => __( 'Bouvet Island', 'wp-easycart' ),
	'BR' => __( 'Brazil', 'wp-easycart' ),
	'IO' => __( 'British Indian Ocean Territory', 'wp-easycart' ),
	'VG' => __( 'British Virgin Islands', 'wp-easycart' ),
	'BN' => __( 'Brunei', 'wp-easycart' ),
	'BG' => __( 'Bulgaria', 'wp-easycart' ),
	'BF' => __( 'Burkina Faso', 'wp-easycart' ),
	'BI' => __( 'Burundi', 'wp-easycart' ),
	'KH' => __( 'Cambodia', 'wp-easycart' ),
	'CM' => __( 'Cameroon', 'wp-easycart' ),
	'CA' => __( 'Canada', 'wp-easycart' ),
	'CV' => __( 'Cape Verde', 'wp-easycart' ),
	'KY' => __( 'Cayman Islands', 'wp-easycart' ),
	'CF' => __( 'Central African Republic', 'wp-easycart' ),
	'TD' => __( 'Chad', 'wp-easycart' ),
	'CL' => __( 'Chile', 'wp-easycart' ),
	'CN' => __( 'China', 'wp-easycart' ),
	'CX' => __( 'Christmas Island', 'wp-easycart' ),
	'CC' => __( 'Cocos (Keeling) Islands', 'wp-easycart' ),
	'CO' => __( 'Colombia', 'wp-easycart' ),
	'KM' => __( 'Comoros', 'wp-easycart' ),
	'CG' => __( 'Congo (Brazzaville)', 'wp-easycart' ),
	'CD' => __( 'Congo (Kinshasa)', 'wp-easycart' ),
	'CK' => __( 'Cook Islands', 'wp-easycart' ),
	'CR' => __( 'Costa Rica', 'wp-easycart' ),
	'HR' => __( 'Croatia', 'wp-easycart' ),
	'CU' => __( 'Cuba', 'wp-easycart' ),
	'CW' => __( 'Cura&ccedil;ao', 'wp-easycart' ),
	'CY' => __( 'Cyprus', 'wp-easycart' ),
	'CZ' => __( 'Czech Republic', 'wp-easycart' ),
	'DK' => __( 'Denmark', 'wp-easycart' ),
	'DJ' => __( 'Djibouti', 'wp-easycart' ),
	'DM' => __( 'Dominica', 'wp-easycart' ),
	'DO' => __( 'Dominican Republic', 'wp-easycart' ),
	'EC' => __( 'Ecuador', 'wp-easycart' ),
	'EG' => __( 'Egypt', 'wp-easycart' ),
	'SV' => __( 'El Salvador', 'wp-easycart' ),
	'GQ' => __( 'Equatorial Guinea', 'wp-easycart' ),
	'ER' => __( 'Eritrea', 'wp-easycart' ),
	'EE' => __( 'Estonia', 'wp-easycart' ),
	'ET' => __( 'Ethiopia', 'wp-easycart' ),
	'FK' => __( 'Falkland Islands', 'wp-easycart' ),
	'FO' => __( 'Faroe Islands', 'wp-easycart' ),
	'FJ' => __( 'Fiji', 'wp-easycart' ),
	'FI' => __( 'Finland', 'wp-easycart' ),
	'FR' => __( 'France', 'wp-easycart' ),
	'GF' => __( 'French Guiana', 'wp-easycart' ),
	'PF' => __( 'French Polynesia', 'wp-easycart' ),
	'TF' => __( 'French Southern Territories', 'wp-easycart' ),
	'GA' => __( 'Gabon', 'wp-easycart' ),
	'GM' => __( 'Gambia', 'wp-easycart' ),
	'GE' => __( 'Georgia', 'wp-easycart' ),
	'DE' => __( 'Germany', 'wp-easycart' ),
	'GH' => __( 'Ghana', 'wp-easycart' ),
	'GI' => __( 'Gibraltar', 'wp-easycart' ),
	'GR' => __( 'Greece', 'wp-easycart' ),
	'GL' => __( 'Greenland', 'wp-easycart' ),
	'GD' => __( 'Grenada', 'wp-easycart' ),
	'GP' => __( 'Guadeloupe', 'wp-easycart' ),
	'GU' => __( 'Guam', 'wp-easycart' ),
	'GT' => __( 'Guatemala', 'wp-easycart' ),
	'GG' => __( 'Guernsey', 'wp-easycart' ),
	'GN' => __( 'Guinea', 'wp-easycart' ),
	'GW' => __( 'Guinea-Bissau', 'wp-easycart' ),
	'GY' => __( 'Guyana', 'wp-easycart' ),
	'HT' => __( 'Haiti', 'wp-easycart' ),
	'HM' => __( 'Heard Island and McDonald Islands', 'wp-easycart' ),
	'HN' => __( 'Honduras', 'wp-easycart' ),
	'HK' => __( 'Hong Kong', 'wp-easycart' ),
	'HU' => __( 'Hungary', 'wp-easycart' ),
	'IS' => __( 'Iceland', 'wp-easycart' ),
	'IN' => __( 'India', 'wp-easycart' ),
	'ID' => __( 'Indonesia', 'wp-easycart' ),
	'IR' => __( 'Iran', 'wp-easycart' ),
	'IQ' => __( 'Iraq', 'wp-easycart' ),
	'IE' => __( 'Ireland', 'wp-easycart' ),
	'IM' => __( 'Isle of Man', 'wp-easycart' ),
	'IL' => __( 'Israel', 'wp-easycart' ),
	'IT' => __( 'Italy', 'wp-easycart' ),
	'CI' => __( 'Ivory Coast', 'wp-easycart' ),
	'JM' => __( 'Jamaica', 'wp-easycart' ),
	'JP' => __( 'Japan', 'wp-easycart' ),
	'JE' => __( 'Jersey', 'wp-easycart' ),
	'JO' => __( 'Jordan', 'wp-easycart' ),
	'KZ' => __( 'Kazakhstan', 'wp-easycart' ),
	'KE' => __( 'Kenya', 'wp-easycart' ),
	'KI' => __( 'Kiribati', 'wp-easycart' ),
	'KW' => __( 'Kuwait', 'wp-easycart' ),
	'KG' => __( 'Kyrgyzstan', 'wp-easycart' ),
	'LA' => __( 'Laos', 'wp-easycart' ),
	'LV' => __( 'Latvia', 'wp-easycart' ),
	'LB' => __( 'Lebanon', 'wp-easycart' ),
	'LS' => __( 'Lesotho', 'wp-easycart' ),
	'LR' => __( 'Liberia', 'wp-easycart' ),
	'LY' => __( 'Libya', 'wp-easycart' ),
	'LI' => __( 'Liechtenstein', 'wp-easycart' ),
	'LT' => __( 'Lithuania', 'wp-easycart' ),
	'LU' => __( 'Luxembourg', 'wp-easycart' ),
	'MO' => __( 'Macao S.A.R., China', 'wp-easycart' ),
	'MK' => __( 'Macedonia', 'wp-easycart' ),
	'MG' => __( 'Madagascar', 'wp-easycart' ),
	'MW' => __( 'Malawi', 'wp-easycart' ),
	'MY' => __( 'Malaysia', 'wp-easycart' ),
	'MV' => __( 'Maldives', 'wp-easycart' ),
	'ML' => __( 'Mali', 'wp-easycart' ),
	'MT' => __( 'Malta', 'wp-easycart' ),
	'MH' => __( 'Marshall Islands', 'wp-easycart' ),
	'MQ' => __( 'Martinique', 'wp-easycart' ),
	'MR' => __( 'Mauritania', 'wp-easycart' ),
	'MU' => __( 'Mauritius', 'wp-easycart' ),
	'YT' => __( 'Mayotte', 'wp-easycart' ),
	'MX' => __( 'Mexico', 'wp-easycart' ),
	'FM' => __( 'Micronesia', 'wp-easycart' ),
	'MD' => __( 'Moldova', 'wp-easycart' ),
	'MC' => __( 'Monaco', 'wp-easycart' ),
	'MN' => __( 'Mongolia', 'wp-easycart' ),
	'ME' => __( 'Montenegro', 'wp-easycart' ),
	'MS' => __( 'Montserrat', 'wp-easycart' ),
	'MA' => __( 'Morocco', 'wp-easycart' ),
	'MZ' => __( 'Mozambique', 'wp-easycart' ),
	'MM' => __( 'Myanmar', 'wp-easycart' ),
	'NA' => __( 'Namibia', 'wp-easycart' ),
	'NR' => __( 'Nauru', 'wp-easycart' ),
	'NP' => __( 'Nepal', 'wp-easycart' ),
	'NL' => __( 'Netherlands', 'wp-easycart' ),
	'NC' => __( 'New Caledonia', 'wp-easycart' ),
	'NZ' => __( 'New Zealand', 'wp-easycart' ),
	'NI' => __( 'Nicaragua', 'wp-easycart' ),
	'NE' => __( 'Niger', 'wp-easycart' ),
	'NG' => __( 'Nigeria', 'wp-easycart' ),
	'NU' => __( 'Niue', 'wp-easycart' ),
	'NF' => __( 'Norfolk Island', 'wp-easycart' ),
	'MP' => __( 'Northern Mariana Islands', 'wp-easycart' ),
	'KP' => __( 'North Korea', 'wp-easycart' ),
	'NO' => __( 'Norway', 'wp-easycart' ),
	'OM' => __( 'Oman', 'wp-easycart' ),
	'PK' => __( 'Pakistan', 'wp-easycart' ),
	'PS' => __( 'Palestinian Territory', 'wp-easycart' ),
	'PA' => __( 'Panama', 'wp-easycart' ),
	'PG' => __( 'Papua New Guinea', 'wp-easycart' ),
	'PY' => __( 'Paraguay', 'wp-easycart' ),
	'PE' => __( 'Peru', 'wp-easycart' ),
	'PH' => __( 'Philippines', 'wp-easycart' ),
	'PN' => __( 'Pitcairn', 'wp-easycart' ),
	'PL' => __( 'Poland', 'wp-easycart' ),
	'PT' => __( 'Portugal', 'wp-easycart' ),
	'PR' => __( 'Puerto Rico', 'wp-easycart' ),
	'QA' => __( 'Qatar', 'wp-easycart' ),
	'RE' => __( 'Reunion', 'wp-easycart' ),
	'RO' => __( 'Romania', 'wp-easycart' ),
	'RU' => __( 'Russia', 'wp-easycart' ),
	'RW' => __( 'Rwanda', 'wp-easycart' ),
	'BL' => __( 'Saint Barth&eacute;lemy', 'wp-easycart' ),
	'SH' => __( 'Saint Helena', 'wp-easycart' ),
	'KN' => __( 'Saint Kitts and Nevis', 'wp-easycart' ),
	'LC' => __( 'Saint Lucia', 'wp-easycart' ),
	'MF' => __( 'Saint Martin (French part)', 'wp-easycart' ),
	'SX' => __( 'Saint Martin (Dutch part)', 'wp-easycart' ),
	'PM' => __( 'Saint Pierre and Miquelon', 'wp-easycart' ),
	'VC' => __( 'Saint Vincent and the Grenadines', 'wp-easycart' ),
	'SM' => __( 'San Marino', 'wp-easycart' ),
	'ST' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'wp-easycart' ),
	'SA' => __( 'Saudi Arabia', 'wp-easycart' ),
	'SN' => __( 'Senegal', 'wp-easycart' ),
	'RS' => __( 'Serbia', 'wp-easycart' ),
	'SC' => __( 'Seychelles', 'wp-easycart' ),
	'SL' => __( 'Sierra Leone', 'wp-easycart' ),
	'SG' => __( 'Singapore', 'wp-easycart' ),
	'SK' => __( 'Slovakia', 'wp-easycart' ),
	'SI' => __( 'Slovenia', 'wp-easycart' ),
	'SB' => __( 'Solomon Islands', 'wp-easycart' ),
	'SO' => __( 'Somalia', 'wp-easycart' ),
	'ZA' => __( 'South Africa', 'wp-easycart' ),
	'GS' => __( 'South Georgia/Sandwich Islands', 'wp-easycart' ),
	'KR' => __( 'South Korea', 'wp-easycart' ),
	'SS' => __( 'South Sudan', 'wp-easycart' ),
	'ES' => __( 'Spain', 'wp-easycart' ),
	'LK' => __( 'Sri Lanka', 'wp-easycart' ),
	'SD' => __( 'Sudan', 'wp-easycart' ),
	'SR' => __( 'Suriname', 'wp-easycart' ),
	'SJ' => __( 'Svalbard and Jan Mayen', 'wp-easycart' ),
	'SZ' => __( 'Swaziland', 'wp-easycart' ),
	'SE' => __( 'Sweden', 'wp-easycart' ),
	'CH' => __( 'Switzerland', 'wp-easycart' ),
	'SY' => __( 'Syria', 'wp-easycart' ),
	'TW' => __( 'Taiwan', 'wp-easycart' ),
	'TJ' => __( 'Tajikistan', 'wp-easycart' ),
	'TZ' => __( 'Tanzania', 'wp-easycart' ),
	'TH' => __( 'Thailand', 'wp-easycart' ),
	'TL' => __( 'Timor-Leste', 'wp-easycart' ),
	'TG' => __( 'Togo', 'wp-easycart' ),
	'TK' => __( 'Tokelau', 'wp-easycart' ),
	'TO' => __( 'Tonga', 'wp-easycart' ),
	'TT' => __( 'Trinidad and Tobago', 'wp-easycart' ),
	'TN' => __( 'Tunisia', 'wp-easycart' ),
	'TR' => __( 'Turkey', 'wp-easycart' ),
	'TM' => __( 'Turkmenistan', 'wp-easycart' ),
	'TC' => __( 'Turks and Caicos Islands', 'wp-easycart' ),
	'TV' => __( 'Tuvalu', 'wp-easycart' ),
	'UG' => __( 'Uganda', 'wp-easycart' ),
	'UA' => __( 'Ukraine', 'wp-easycart' ),
	'AE' => __( 'United Arab Emirates', 'wp-easycart' ),
	'GB' => __( 'United Kingdom (UK)', 'wp-easycart' ),
	'US' => __( 'United States (US)', 'wp-easycart' ),
	'UM' => __( 'United States (US) Minor Outlying Islands', 'wp-easycart' ),
	'VI' => __( 'United States (US) Virgin Islands', 'wp-easycart' ),
	'UY' => __( 'Uruguay', 'wp-easycart' ),
	'UZ' => __( 'Uzbekistan', 'wp-easycart' ),
	'VU' => __( 'Vanuatu', 'wp-easycart' ),
	'VA' => __( 'Vatican', 'wp-easycart' ),
	'VE' => __( 'Venezuela', 'wp-easycart' ),
	'VN' => __( 'Vietnam', 'wp-easycart' ),
	'WF' => __( 'Wallis and Futuna', 'wp-easycart' ),
	'EH' => __( 'Western Sahara', 'wp-easycart' ),
	'WS' => __( 'Samoa', 'wp-easycart' ),
	'YE' => __( 'Yemen', 'wp-easycart' ),
	'ZM' => __( 'Zambia', 'wp-easycart' ),
	'ZW' => __( 'Zimbabwe', 'wp-easycart' ),
);
$locales =  array(
	'US' => array(
		'currency_code'  => 'USD',
		'currency_pos'	=> 'left',
		'thousand_sep'	=> ',',
		'decimal_sep'	 => '.',
		'num_decimals'	=> 2,
		'weight_unit'	 => 'lbs',
		'dimension_unit' => 'in',
		'tax_rates'		=> array(
			'AL' => array(
				array(
					'country'  => 'US',
					'state'    => 'AL',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'AZ' => array(
				array(
					'country'  => 'US',
					'state'    => 'AZ',
					'rate'     => '5.6000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'AR' => array(
				array(
					'country'  => 'US',
					'state'    => 'AR',
					'rate'     => '6.5000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'CA' => array(
				array(
					'country'  => 'US',
					'state'    => 'CA',
					'rate'     => '7.5000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'CO' => array(
				array(
					'country'  => 'US',
					'state'    => 'CO',
					'rate'     => '2.9000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'CT' => array(
				array(
					'country'  => 'US',
					'state'    => 'CT',
					'rate'     => '6.3500',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'DC' => array(
				array(
					'country'  => 'US',
					'state'    => 'DC',
					'rate'     => '5.7500',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'FL' => array(
				array(
					'country'  => 'US',
					'state'    => 'FL',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'GA' => array(
				array(
					'country'  => 'US',
					'state'    => 'GA',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'GU' => array(
				array(
					'country'  => 'US',
					'state'    => 'GU',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'HI' => array(
				array(
					'country'  => 'US',
					'state'    => 'HI',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'ID' => array(
				array(
					'country'  => 'US',
					'state'    => 'ID',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'IL' => array(
				array(
					'country'  => 'US',
					'state'    => 'IL',
					'rate'     => '6.2500',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'IN' => array(
				array(
					'country'  => 'US',
					'state'    => 'IN',
					'rate'     => '7.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'IA' => array(
				array(
					'country'  => 'US',
					'state'    => 'IA',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'KS' => array(
				array(
					'country'  => 'US',
					'state'    => 'KS',
					'rate'     => '6.1500',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'KY' => array(
				array(
					'country'  => 'US',
					'state'    => 'KY',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'LA' => array(
				array(
					'country'  => 'US',
					'state'    => 'LA',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'ME' => array(
				array(
					'country'  => 'US',
					'state'    => 'ME',
					'rate'     => '5.5000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'MD' => array(
				array(
					'country'  => 'US',
					'state'    => 'MD',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'MA' => array(
				array(
					'country'  => 'US',
					'state'    => 'MA',
					'rate'     => '6.2500',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'MI' => array(
				array(
					'country'  => 'US',
					'state'    => 'MI',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'MN' => array(
				array(
					'country'  => 'US',
					'state'    => 'MN',
					'rate'     => '6.8750',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'MS' => array(
				array(
					'country'  => 'US',
					'state'    => 'MS',
					'rate'     => '7.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'MO' => array(
				array(
					'country'  => 'US',
					'state'    => 'MO',
					'rate'     => '4.225',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'NE' => array(
				array(
					'country'  => 'US',
					'state'    => 'NE',
					'rate'     => '5.5000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'NV' => array(
				array(
					'country'  => 'US',
					'state'    => 'NV',
					'rate'     => '6.8500',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'NJ' => array(
				array(
					'country'  => 'US',
					'state'    => 'NJ',
					'rate'     => '7.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'NM' => array(
				array(
					'country'  => 'US',
					'state'    => 'NM',
					'rate'     => '5.1250',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'NY' => array(
				array(
					'country'  => 'US',
					'state'    => 'NY',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'NC' => array(
				array(
					'country'  => 'US',
					'state'    => 'NC',
					'rate'     => '4.7500',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'ND' => array(
				array(
					'country'  => 'US',
					'state'    => 'ND',
					'rate'     => '5.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'OH' => array(
				array(
					'country'  => 'US',
					'state'    => 'OH',
					'rate'     => '5.7500',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'OK' => array(
				array(
					'country'  => 'US',
					'state'    => 'OK',
					'rate'     => '4.5000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'PA' => array(
				array(
					'country'  => 'US',
					'state'    => 'PA',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'PR' => array(
				array(
					'country'  => 'US',
					'state'    => 'PR',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'RI' => array(
				array(
					'country'  => 'US',
					'state'    => 'RI',
					'rate'     => '7.0000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'SC' => array(
				array(
					'country'  => 'US',
					'state'    => 'SC',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'SD' => array(
				array(
					'country'  => 'US',
					'state'    => 'SD',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'TN' => array(
				array(
					'country'  => 'US',
					'state'    => 'TN',
					'rate'     => '7.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'TX' => array(
				array(
					'country'  => 'US',
					'state'    => 'TX',
					'rate'     => '6.2500',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'UT' => array(
				array(
					'country'  => 'US',
					'state'    => 'UT',
					'rate'     => '5.9500',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'VT' => array(
				array(
					'country'  => 'US',
					'state'    => 'VT',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'VA' => array(
				array(
					'country'  => 'US',
					'state'    => 'VA',
					'rate'     => '5.3000',
					'name'     => 'State Tax',
					'shipping' => false,
				),
			),
			'WA' => array(
				array(
					'country'  => 'US',
					'state'    => 'WA',
					'rate'     => '6.5000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'WV' => array(
				array(
					'country'  => 'US',
					'state'    => 'WV',
					'rate'     => '6.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'WI' => array(
				array(
					'country'  => 'US',
					'state'    => 'WI',
					'rate'     => '5.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
			'WY' => array(
				array(
					'country'  => 'US',
					'state'    => 'WY',
					'rate'     => '4.0000',
					'name'     => 'State Tax',
					'shipping' => true,
				),
			),
		),
	),
	'CA' => array(
		'currency_code'  => 'CAD',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'BC' => array(
				array(
					'country'  => 'CA',
					'state'    => 'BC',
					'rate'     => '7.0000',
					'name'     => _x( 'PST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => false,
					'priority' => 2,
				),
			),
			'SK' => array(
				array(
					'country'  => 'CA',
					'state'    => 'SK',
					'rate'     => '5.0000',
					'name'     => _x( 'PST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => false,
					'priority' => 2,
				),
			),
			'MB' => array(
				array(
					'country'  => 'CA',
					'state'    => 'MB',
					'rate'     => '8.0000',
					'name'     => _x( 'PST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => false,
					'priority' => 2,
				),
			),
			'QC' => array(
				array(
					'country'  => 'CA',
					'state'    => 'QC',
					'rate'     => '9.975',
					'name'     => _x( 'PST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => false,
					'priority' => 2,
				),
			),
			'*' => array(
				array(
					'country'  => 'CA',
					'state'    => 'ON',
					'rate'     => '13.0000',
					'name'     => _x( 'HST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'NL',
					'rate'     => '13.0000',
					'name'     => _x( 'HST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'NB',
					'rate'     => '13.0000',
					'name'     => _x( 'HST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'PE',
					'rate'     => '14.0000',
					'name'     => _x( 'HST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'NS',
					'rate'     => '15.0000',
					'name'     => _x( 'HST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'AB',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'BC',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'NT',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'NU',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'YT',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'SK',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'MB',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
				array(
					'country'  => 'CA',
					'state'    => 'QC',
					'rate'     => '5.0000',
					'name'     => _x( 'GST', 'Canadian Tax Rates', 'wp-easycart' ),
					'shipping' => true,
				),
			),
		),
	),
	'AU' => array(
		'currency_code'  => 'AUD',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'AU',
					'state'    => '',
					'rate'     => '10.0000',
					'name'     => 'GST',
					'shipping' => true,
				),
			),
		),
	),
	'BD' => array(
		'currency_code'  => 'BDT',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'in',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'BD',
					'state'    => '',
					'rate'     => '15.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'BE' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'left',
		'thousand_sep'   => ' ',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
			  array(
					'country'  => 'BE',
					'state'    => '',
					'rate'     => '21.0000',
					'name'     => 'BTW',
					'shipping' => true,
				),
			),
		),
	),
	'BR' => array(
		'currency_code'  => 'BRL',
		'currency_pos'   => 'left',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(),
	),
	'DE' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'left',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'DE',
					'state'    => '',
					'rate'     => '19.0000',
					'name'     => 'Mwst.',
					'shipping' => true,
				),
			),
		),
	),
	'ES' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'right',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'ES',
					'state'    => '',
					'rate'     => '21.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'FI' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'right_space',
		'thousand_sep'   => ' ',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'FI',
					'state'    => '',
					'rate'     => '24.0000',
					'name'     => 'ALV',
					'shipping' => true,
				),
			),
		),
	),
	'FR' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'right',
		'thousand_sep'   => ' ',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'FR',
					'state'    => '',
					'rate'     => '20.0000',
					'name'     => 'TVA',
					'shipping' => true,
				),
			),
		),
	),
	'GB' => array(
		'currency_code'  => 'GBP',
		'currency_pos'	=> 'left',
		'thousand_sep'	=> ',',
		'decimal_sep'	 => '.',
		'num_decimals'	=> 2,
		'weight_unit'	 => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'		=> array(
			'' => array(
				array(
					'country'  => 'GB',
					'state'	 => '',
					'rate'	  => '20.0000',
					'name'	  => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'HU' => array(
		'currency_code'  => 'HUF',
		'currency_pos'   => 'right_space',
		'thousand_sep'   => ' ',
		'decimal_sep'    => ',',
		'num_decimals'   => 0,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'HU',
					'state'    => '',
					'rate'     => '27.0000',
					'name'     => 'ÁFA',
					'shipping' => true,
				),
			),
		),
	),
	'IT' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'right',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'IT',
					'state'    => '',
					'rate'     => '22.0000',
					'name'     => 'IVA',
					'shipping' => true,
				),
			),
		),
	),
	'JP' => array(
		'currency_code'  => 'JPY',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 0,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'JP',
					'state'    => '',
					'rate'     => '8.0000',
					'name'     => __( 'Consumption tax', 'wp-easycart' ),
					'shipping' => true,
				),
			),
		),
	),
	'NL' => array(
		'currency_code'  => 'EUR',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'NL',
					'state'    => '',
					'rate'     => '21.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'NO' => array(
		'currency_code'  => 'Kr',
		'currency_pos'   => 'left_space',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'NO',
					'state'    => '',
					'rate'     => '25.0000',
					'name'     => 'MVA',
					'shipping' => true,
				),
			),
		),
	),
	'NP' => array(
		'currency_code'  => 'NPR',
		'currency_pos'   => 'left_space',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'NP',
					'state'    => '',
					'rate'     => '13.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'PL' => array(
		'currency_code'  => 'PLN',
		'currency_pos'   => 'right_space',
		'thousand_sep'   => ' ',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
			 	array(
					'country'  => 'PL',
					'state'    => '',
					'rate'     => '23.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'RO' => array(
		'currency_code'  => 'RON',
		'currency_pos'   => 'right_space',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'RO',
					'state'    => '',
					'rate'     => '19.0000',
					'name'     => 'TVA',
					'shipping' => true,
				),
			),
		),
	),
	'TH' => array(
		'currency_code'  => 'THB',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'TH',
					'state'    => '',
					'rate'     => '7.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
	'TR' => array(
		'currency_code'  => 'TRY',
		'currency_pos'   => 'left_space',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'TR',
					'state'    => '',
					'rate'     => '18.0000',
					'name'     => 'KDV',
					'shipping' => true,
				),
			),
		),
	),
	'ZA' => array(
		'currency_code'  => 'ZAR',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'ZA',
					'state'    => '',
					'rate'     => '14.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
);
$states['US'] = array(
	'AL' => __( 'Alabama', 'wp-easycart' ),
	'AK' => __( 'Alaska', 'wp-easycart' ),
	'AZ' => __( 'Arizona', 'wp-easycart' ),
	'AR' => __( 'Arkansas', 'wp-easycart' ),
	'CA' => __( 'California', 'wp-easycart' ),
	'CO' => __( 'Colorado', 'wp-easycart' ),
	'CT' => __( 'Connecticut', 'wp-easycart' ),
	'DE' => __( 'Delaware', 'wp-easycart' ),
	'DC' => __( 'District Of Columbia', 'wp-easycart' ),
	'FL' => __( 'Florida', 'wp-easycart' ),
	'GA' => _x( 'Georgia', 'US state of Georgia', 'wp-easycart' ),
	'HI' => __( 'Hawaii', 'wp-easycart' ),
	'ID' => __( 'Idaho', 'wp-easycart' ),
	'IL' => __( 'Illinois', 'wp-easycart' ),
	'IN' => __( 'Indiana', 'wp-easycart' ),
	'IA' => __( 'Iowa', 'wp-easycart' ),
	'KS' => __( 'Kansas', 'wp-easycart' ),
	'KY' => __( 'Kentucky', 'wp-easycart' ),
	'LA' => __( 'Louisiana', 'wp-easycart' ),
	'ME' => __( 'Maine', 'wp-easycart' ),
	'MD' => __( 'Maryland', 'wp-easycart' ),
	'MA' => __( 'Massachusetts', 'wp-easycart' ),
	'MI' => __( 'Michigan', 'wp-easycart' ),
	'MN' => __( 'Minnesota', 'wp-easycart' ),
	'MS' => __( 'Mississippi', 'wp-easycart' ),
	'MO' => __( 'Missouri', 'wp-easycart' ),
	'MT' => __( 'Montana', 'wp-easycart' ),
	'NE' => __( 'Nebraska', 'wp-easycart' ),
	'NV' => __( 'Nevada', 'wp-easycart' ),
	'NH' => __( 'New Hampshire', 'wp-easycart' ),
	'NJ' => __( 'New Jersey', 'wp-easycart' ),
	'NM' => __( 'New Mexico', 'wp-easycart' ),
	'NY' => __( 'New York', 'wp-easycart' ),
	'NC' => __( 'North Carolina', 'wp-easycart' ),
	'ND' => __( 'North Dakota', 'wp-easycart' ),
	'OH' => __( 'Ohio', 'wp-easycart' ),
	'OK' => __( 'Oklahoma', 'wp-easycart' ),
	'OR' => __( 'Oregon', 'wp-easycart' ),
	'PA' => __( 'Pennsylvania', 'wp-easycart' ),
	'RI' => __( 'Rhode Island', 'wp-easycart' ),
	'SC' => __( 'South Carolina', 'wp-easycart' ),
	'SD' => __( 'South Dakota', 'wp-easycart' ),
	'TN' => __( 'Tennessee', 'wp-easycart' ),
	'TX' => __( 'Texas', 'wp-easycart' ),
	'UT' => __( 'Utah', 'wp-easycart' ),
	'VT' => __( 'Vermont', 'wp-easycart' ),
	'VA' => __( 'Virginia', 'wp-easycart' ),
	'WA' => __( 'Washington', 'wp-easycart' ),
	'WV' => __( 'West Virginia', 'wp-easycart' ),
	'WI' => __( 'Wisconsin', 'wp-easycart' ),
	'WY' => __( 'Wyoming', 'wp-easycart' ),
	'AA' => __( 'Armed Forces (AA)', 'wp-easycart' ),
	'AE' => __( 'Armed Forces (AE)', 'wp-easycart' ),
	'AP' => __( 'Armed Forces (AP)', 'wp-easycart' ),
);
$currency_names = array(
	'USD' => __( 'United States dollar', 'wp-easycart' ),
	'CAD' => __( 'Canadian dollar', 'wp-easycart' ),
	'EUR' => __( 'Euro', 'wp-easycart' ),
	'GBP' => __( 'Pound sterling', 'wp-easycart' ),
	'AUD' => __( 'Australian dollar', 'wp-easycart' ),
	'AED' => __( 'United Arab Emirates dirham', 'wp-easycart' ),
	'AFN' => __( 'Afghan afghani', 'wp-easycart' ),
	'ALL' => __( 'Albanian lek', 'wp-easycart' ),
	'AMD' => __( 'Armenian dram', 'wp-easycart' ),
	'ANG' => __( 'Netherlands Antillean guilder', 'wp-easycart' ),
	'AOA' => __( 'Angolan kwanza', 'wp-easycart' ),
	'ARS' => __( 'Argentine peso', 'wp-easycart' ),
	'AWG' => __( 'Aruban florin', 'wp-easycart' ),
	'AUD' => __( 'Australian dollar', 'wp-easycart' ),
	'AZN' => __( 'Azerbaijani manat', 'wp-easycart' ),
	'BAM' => __( 'Bosnia and Herzegovina convertible mark', 'wp-easycart' ),
	'BBD' => __( 'Barbadian dollar', 'wp-easycart' ),
	'BDT' => __( 'Bangladeshi taka', 'wp-easycart' ),
	'BGN' => __( 'Bulgarian lev', 'wp-easycart' ),
	'BHD' => __( 'Bahraini dinar', 'wp-easycart' ),
	'BIF' => __( 'Burundian franc', 'wp-easycart' ),
	'BMD' => __( 'Bermudian dollar', 'wp-easycart' ),
	'BND' => __( 'Brunei dollar', 'wp-easycart' ),
	'BOB' => __( 'Bolivian boliviano', 'wp-easycart' ),
	'BRL' => __( 'Brazilian real', 'wp-easycart' ),
	'BSD' => __( 'Bahamian dollar', 'wp-easycart' ),
	'BTC' => __( 'Bitcoin', 'wp-easycart' ),
	'BTN' => __( 'Bhutanese ngultrum', 'wp-easycart' ),
	'BWP' => __( 'Botswana pula', 'wp-easycart' ),
	'BYR' => __( 'Belarusian ruble', 'wp-easycart' ),
	'BZD' => __( 'Belize dollar', 'wp-easycart' ),
	'CAD' => __( 'Canadian dollar', 'wp-easycart' ),
	'CDF' => __( 'Congolese franc', 'wp-easycart' ),
	'CHF' => __( 'Swiss franc', 'wp-easycart' ),
	'CLP' => __( 'Chilean peso', 'wp-easycart' ),
	'CNY' => __( 'Chinese yuan', 'wp-easycart' ),
	'COP' => __( 'Colombian peso', 'wp-easycart' ),
	'CRC' => __( 'Costa Rican col&oacute;n', 'wp-easycart' ),
	'CUC' => __( 'Cuban convertible peso', 'wp-easycart' ),
	'CUP' => __( 'Cuban peso', 'wp-easycart' ),
	'CVE' => __( 'Cape Verdean escudo', 'wp-easycart' ),
	'CZK' => __( 'Czech koruna', 'wp-easycart' ),
	'DJF' => __( 'Djiboutian franc', 'wp-easycart' ),
	'DKK' => __( 'Danish krone', 'wp-easycart' ),
	'DOP' => __( 'Dominican peso', 'wp-easycart' ),
	'DZD' => __( 'Algerian dinar', 'wp-easycart' ),
	'EGP' => __( 'Egyptian pound', 'wp-easycart' ),
	'ERN' => __( 'Eritrean nakfa', 'wp-easycart' ),
	'ETB' => __( 'Ethiopian birr', 'wp-easycart' ),
	'EUR' => __( 'Euro', 'wp-easycart' ),
	'FJD' => __( 'Fijian dollar', 'wp-easycart' ),
	'FKP' => __( 'Falkland Islands pound', 'wp-easycart' ),
	'GEL' => __( 'Georgian lari', 'wp-easycart' ),
	'GGP' => __( 'Guernsey pound', 'wp-easycart' ),
	'GHS' => __( 'Ghana cedi', 'wp-easycart' ),
	'GIP' => __( 'Gibraltar pound', 'wp-easycart' ),
	'GMD' => __( 'Gambian dalasi', 'wp-easycart' ),
	'GNF' => __( 'Guinean franc', 'wp-easycart' ),
	'GTQ' => __( 'Guatemalan quetzal', 'wp-easycart' ),
	'GYD' => __( 'Guyanese dollar', 'wp-easycart' ),
	'HKD' => __( 'Hong Kong dollar', 'wp-easycart' ),
	'HNL' => __( 'Honduran lempira', 'wp-easycart' ),
	'HRK' => __( 'Croatian kuna', 'wp-easycart' ),
	'HTG' => __( 'Haitian gourde', 'wp-easycart' ),
	'HUF' => __( 'Hungarian forint', 'wp-easycart' ),
	'IDR' => __( 'Indonesian rupiah', 'wp-easycart' ),
	'ILS' => __( 'Israeli new shekel', 'wp-easycart' ),
	'IMP' => __( 'Manx pound', 'wp-easycart' ),
	'INR' => __( 'Indian rupee', 'wp-easycart' ),
	'IQD' => __( 'Iraqi dinar', 'wp-easycart' ),
	'IRR' => __( 'Iranian rial', 'wp-easycart' ),
	'IRT' => __( 'Iranian toman', 'wp-easycart' ),
	'ISK' => __( 'Icelandic kr&oacute;na', 'wp-easycart' ),
	'JEP' => __( 'Jersey pound', 'wp-easycart' ),
	'JMD' => __( 'Jamaican dollar', 'wp-easycart' ),
	'JOD' => __( 'Jordanian dinar', 'wp-easycart' ),
	'JPY' => __( 'Japanese yen', 'wp-easycart' ),
	'KES' => __( 'Kenyan shilling', 'wp-easycart' ),
	'KGS' => __( 'Kyrgyzstani som', 'wp-easycart' ),
	'KHR' => __( 'Cambodian riel', 'wp-easycart' ),
	'KMF' => __( 'Comorian franc', 'wp-easycart' ),
	'KPW' => __( 'North Korean won', 'wp-easycart' ),
	'KRW' => __( 'South Korean won', 'wp-easycart' ),
	'KWD' => __( 'Kuwaiti dinar', 'wp-easycart' ),
	'KYD' => __( 'Cayman Islands dollar', 'wp-easycart' ),
	'KZT' => __( 'Kazakhstani tenge', 'wp-easycart' ),
	'LAK' => __( 'Lao kip', 'wp-easycart' ),
	'LBP' => __( 'Lebanese pound', 'wp-easycart' ),
	'LKR' => __( 'Sri Lankan rupee', 'wp-easycart' ),
	'LRD' => __( 'Liberian dollar', 'wp-easycart' ),
	'LSL' => __( 'Lesotho loti', 'wp-easycart' ),
	'LYD' => __( 'Libyan dinar', 'wp-easycart' ),
	'MAD' => __( 'Moroccan dirham', 'wp-easycart' ),
	'MDL' => __( 'Moldovan leu', 'wp-easycart' ),
	'MGA' => __( 'Malagasy ariary', 'wp-easycart' ),
	'MKD' => __( 'Macedonian denar', 'wp-easycart' ),
	'MMK' => __( 'Burmese kyat', 'wp-easycart' ),
	'MNT' => __( 'Mongolian t&ouml;gr&ouml;g', 'wp-easycart' ),
	'MOP' => __( 'Macanese pataca', 'wp-easycart' ),
	'MRO' => __( 'Mauritanian ouguiya', 'wp-easycart' ),
	'MUR' => __( 'Mauritian rupee', 'wp-easycart' ),
	'MVR' => __( 'Maldivian rufiyaa', 'wp-easycart' ),
	'MWK' => __( 'Malawian kwacha', 'wp-easycart' ),
	'MXN' => __( 'Mexican peso', 'wp-easycart' ),
	'MYR' => __( 'Malaysian ringgit', 'wp-easycart' ),
	'MZN' => __( 'Mozambican metical', 'wp-easycart' ),
	'NAD' => __( 'Namibian dollar', 'wp-easycart' ),
	'NGN' => __( 'Nigerian naira', 'wp-easycart' ),
	'NIO' => __( 'Nicaraguan c&oacute;rdoba', 'wp-easycart' ),
	'NOK' => __( 'Norwegian krone', 'wp-easycart' ),
	'NPR' => __( 'Nepalese rupee', 'wp-easycart' ),
	'NZD' => __( 'New Zealand dollar', 'wp-easycart' ),
	'OMR' => __( 'Omani rial', 'wp-easycart' ),
	'PAB' => __( 'Panamanian balboa', 'wp-easycart' ),
	'PEN' => __( 'Peruvian nuevo sol', 'wp-easycart' ),
	'PGK' => __( 'Papua New Guinean kina', 'wp-easycart' ),
	'PHP' => __( 'Philippine peso', 'wp-easycart' ),
	'PKR' => __( 'Pakistani rupee', 'wp-easycart' ),
	'PLN' => __( 'Polish z&#x142;oty', 'wp-easycart' ),
	'GBP' => __( 'Pound sterling', 'wp-easycart' ),
	'PRB' => __( 'Transnistrian ruble', 'wp-easycart' ),
	'PYG' => __( 'Paraguayan guaran&iacute;', 'wp-easycart' ),
	'QAR' => __( 'Qatari riyal', 'wp-easycart' ),
	'RON' => __( 'Romanian leu', 'wp-easycart' ),
	'RSD' => __( 'Serbian dinar', 'wp-easycart' ),
	'RUB' => __( 'Russian ruble', 'wp-easycart' ),
	'RWF' => __( 'Rwandan franc', 'wp-easycart' ),
	'SAR' => __( 'Saudi riyal', 'wp-easycart' ),
	'SBD' => __( 'Solomon Islands dollar', 'wp-easycart' ),
	'SCR' => __( 'Seychellois rupee', 'wp-easycart' ),
	'SDG' => __( 'Sudanese pound', 'wp-easycart' ),
	'SEK' => __( 'Swedish krona', 'wp-easycart' ),
	'SGD' => __( 'Singapore dollar', 'wp-easycart' ),
	'SHP' => __( 'Saint Helena pound', 'wp-easycart' ),
	'SLL' => __( 'Sierra Leonean leone', 'wp-easycart' ),
	'SOS' => __( 'Somali shilling', 'wp-easycart' ),
	'SRD' => __( 'Surinamese dollar', 'wp-easycart' ),
	'SSP' => __( 'South Sudanese pound', 'wp-easycart' ),
	'STD' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe dobra', 'wp-easycart' ),
	'SYP' => __( 'Syrian pound', 'wp-easycart' ),
	'SZL' => __( 'Swazi lilangeni', 'wp-easycart' ),
	'THB' => __( 'Thai baht', 'wp-easycart' ),
	'TJS' => __( 'Tajikistani somoni', 'wp-easycart' ),
	'TMT' => __( 'Turkmenistan manat', 'wp-easycart' ),
	'TND' => __( 'Tunisian dinar', 'wp-easycart' ),
	'TOP' => __( 'Tongan pa&#x2bb;anga', 'wp-easycart' ),
	'TRY' => __( 'Turkish lira', 'wp-easycart' ),
	'TTD' => __( 'Trinidad and Tobago dollar', 'wp-easycart' ),
	'TWD' => __( 'New Taiwan dollar', 'wp-easycart' ),
	'TZS' => __( 'Tanzanian shilling', 'wp-easycart' ),
	'UAH' => __( 'Ukrainian hryvnia', 'wp-easycart' ),
	'UGX' => __( 'Ugandan shilling', 'wp-easycart' ),
	'USD' => __( 'United States dollar', 'wp-easycart' ),
	'UYU' => __( 'Uruguayan peso', 'wp-easycart' ),
	'UZS' => __( 'Uzbekistani som', 'wp-easycart' ),
	'VEF' => __( 'Venezuelan bol&iacute;var', 'wp-easycart' ),
	'VND' => __( 'Vietnamese &#x111;&#x1ed3;ng', 'wp-easycart' ),
	'VUV' => __( 'Vanuatu vatu', 'wp-easycart' ),
	'WST' => __( 'Samoan t&#x101;l&#x101;', 'wp-easycart' ),
	'XAF' => __( 'Central African CFA franc', 'wp-easycart' ),
	'XCD' => __( 'East Caribbean dollar', 'wp-easycart' ),
	'XOF' => __( 'West African CFA franc', 'wp-easycart' ),
	'XPF' => __( 'CFP franc', 'wp-easycart' ),
	'YER' => __( 'Yemeni rial', 'wp-easycart' ),
	'ZAR' => __( 'South African rand', 'wp-easycart' ),
	'ZMW' => __( 'Zambian kwacha', 'wp-easycart' ),
);
$currency_symbols = array(
	'AED' => '&#x62f;.&#x625;',
	'AFN' => '&#x60b;',
	'ALL' => 'L',
	'AMD' => 'AMD',
	'ANG' => '&fnof;',
	'AOA' => 'Kz',
	'ARS' => '&#36;',
	'AUD' => '&#36;',
	'AWG' => 'Afl.',
	'AZN' => 'AZN',
	'BAM' => 'KM',
	'BBD' => '&#36;',
	'BDT' => '&#2547;&nbsp;',
	'BGN' => '&#1083;&#1074;.',
	'BHD' => '.&#x62f;.&#x628;',
	'BIF' => 'Fr',
	'BMD' => '&#36;',
	'BND' => '&#36;',
	'BOB' => 'Bs.',
	'BRL' => '&#82;&#36;',
	'BSD' => '&#36;',
	'BTC' => '&#3647;',
	'BTN' => 'Nu.',
	'BWP' => 'P',
	'BYR' => 'Br',
	'BZD' => '&#36;',
	'CAD' => '&#36;',
	'CDF' => 'Fr',
	'CHF' => '&#67;&#72;&#70;',
	'CLP' => '&#36;',
	'CNY' => '&yen;',
	'COP' => '&#36;',
	'CRC' => '&#x20a1;',
	'CUC' => '&#36;',
	'CUP' => '&#36;',
	'CVE' => '&#36;',
	'CZK' => '&#75;&#269;',
	'DJF' => 'Fr',
	'DKK' => 'DKK',
	'DOP' => 'RD&#36;',
	'DZD' => '&#x62f;.&#x62c;',
	'EGP' => 'EGP',
	'ERN' => 'Nfk',
	'ETB' => 'Br',
	'EUR' => '&euro;',
	'FJD' => '&#36;',
	'FKP' => '&pound;',
	'GBP' => '&pound;',
	'GEL' => '&#x10da;',
	'GGP' => '&pound;',
	'GHS' => '&#x20b5;',
	'GIP' => '&pound;',
	'GMD' => 'D',
	'GNF' => 'Fr',
	'GTQ' => 'Q',
	'GYD' => '&#36;',
	'HKD' => '&#36;',
	'HNL' => 'L',
	'HRK' => 'Kn',
	'HTG' => 'G',
	'HUF' => '&#70;&#116;',
	'IDR' => 'Rp',
	'ILS' => '&#8362;',
	'IMP' => '&pound;',
	'INR' => '&#8377;',
	'IQD' => '&#x639;.&#x62f;',
	'IRR' => '&#xfdfc;',
	'IRT' => '&#x062A;&#x0648;&#x0645;&#x0627;&#x0646;',
	'ISK' => 'kr.',
	'JEP' => '&pound;',
	'JMD' => '&#36;',
	'JOD' => '&#x62f;.&#x627;',
	'JPY' => '&yen;',
	'KES' => 'KSh',
	'KGS' => '&#x441;&#x43e;&#x43c;',
	'KHR' => '&#x17db;',
	'KMF' => 'Fr',
	'KPW' => '&#x20a9;',
	'KRW' => '&#8361;',
	'KWD' => '&#x62f;.&#x643;',
	'KYD' => '&#36;',
	'KZT' => 'KZT',
	'LAK' => '&#8365;',
	'LBP' => '&#x644;.&#x644;',
	'LKR' => '&#xdbb;&#xdd4;',
	'LRD' => '&#36;',
	'LSL' => 'L',
	'LYD' => '&#x644;.&#x62f;',
	'MAD' => '&#x62f;.&#x645;.',
	'MDL' => 'MDL',
	'MGA' => 'Ar',
	'MKD' => '&#x434;&#x435;&#x43d;',
	'MMK' => 'Ks',
	'MNT' => '&#x20ae;',
	'MOP' => 'P',
	'MRO' => 'UM',
	'MUR' => '&#x20a8;',
	'MVR' => '.&#x783;',
	'MWK' => 'MK',
	'MXN' => '&#36;',
	'MYR' => '&#82;&#77;',
	'MZN' => 'MT',
	'NAD' => '&#36;',
	'NGN' => '&#8358;',
	'NIO' => 'C&#36;',
	'NOK' => '&#107;&#114;',
	'NPR' => '&#8360;',
	'NZD' => '&#36;',
	'OMR' => '&#x631;.&#x639;.',
	'PAB' => 'B/.',
	'PEN' => 'S/.',
	'PGK' => 'K',
	'PHP' => '&#8369;',
	'PKR' => '&#8360;',
	'PLN' => '&#122;&#322;',
	'PRB' => '&#x440;.',
	'PYG' => '&#8370;',
	'QAR' => '&#x631;.&#x642;',
	'RMB' => '&yen;',
	'RON' => 'lei',
	'RSD' => '&#x434;&#x438;&#x43d;.',
	'RUB' => '&#8381;',
	'RWF' => 'Fr',
	'SAR' => '&#x631;.&#x633;',
	'SBD' => '&#36;',
	'SCR' => '&#x20a8;',
	'SDG' => '&#x62c;.&#x633;.',
	'SEK' => '&#107;&#114;',
	'SGD' => '&#36;',
	'SHP' => '&pound;',
	'SLL' => 'Le',
	'SOS' => 'Sh',
	'SRD' => '&#36;',
	'SSP' => '&pound;',
	'STD' => 'Db',
	'SYP' => '&#x644;.&#x633;',
	'SZL' => 'L',
	'THB' => '&#3647;',
	'TJS' => '&#x405;&#x41c;',
	'TMT' => 'm',
	'TND' => '&#x62f;.&#x62a;',
	'TOP' => 'T&#36;',
	'TRY' => '&#8378;',
	'TTD' => '&#36;',
	'TWD' => '&#78;&#84;&#36;',
	'TZS' => 'Sh',
	'UAH' => '&#8372;',
	'UGX' => 'UGX',
	'USD' => '&#36;',
	'UYU' => '&#36;',
	'UZS' => 'UZS',
	'VEF' => 'Bs F',
	'VND' => '&#8363;',
	'VUV' => 'Vt',
	'WST' => 'T',
	'XAF' => 'CFA',
	'XCD' => '&#36;',
	'XOF' => 'CFA',
	'XPF' => 'Fr',
	'YER' => '&#xfdfc;',
	'ZAR' => '&#82;',
	'ZMW' => 'ZK',
);
?>
<form action="" method="POST" name="wpeasycart_admin_setup_wizard_form" id="wpeasycart_admin_setup_wizard_form" novalidate="novalidate">
<input type="hidden" name="ec_admin_form_action" id="ec_admin_form_action" value="process-wizard-location">
<h3>Store Location &amp; Tax</h3>
<p>Please start by choosing your store location. WP EasyCart will automatically help you determine your basic tax and locale settings.</p>
<div class="ec_admin_wizard_input_row">
	<div class="ec_admin_wizard_input_row_title">Where is your store based?</div>
	<div class="ec_admin_wizard_input_row_input"><select name="locale" id="wp_easycart_locale" class="select2-basic" onchange="wp_easycart_update_wizard_update_tax( );">
    	<?php foreach( $countries as $country_code => $country_name ){ ?>
        <?php if( isset( $states[$country_code] ) ){ ?>
        <?php foreach( $states[$country_code] as $state_code => $state_name ){ ?>
        <option value="<?php echo $country_code; ?>_<?php echo $state_code; ?>"><?php echo $country_name; ?> - <?php echo $state_name; ?></option>
        <?php }?>
        <?php }else{ ?>
        <option value="<?php echo $country_code; ?>"><?php echo $country_name; ?></option>
        <?php }?>
        <?php }?>
    </select></div>
</div>
<div class="ec_admin_wizard_input_row">
	<div class="ec_admin_wizard_input_row_title">Where is your default currency?</div>
	<div class="ec_admin_wizard_input_row_input"><select name="currency" id="wp_easycart_currency" class="select2-basic">
    	<?php foreach( $currency_names as $currency_code => $currency_name ){ ?>
        <option value="<?php echo $currency_code; ?>"><?php echo ucwords( $currency_name ); ?><?php if( isset( $currency_symbols[$currency_code] ) ){ ?> (<?php echo $currency_symbols[$currency_code]; ?>)<?php }?></option>
        <?php }?>
    </select></div>
</div>
<div class="ec_admin_wizard_input_row">
	<div class="ec_admin_wizard_input_row_title">What language do you need?</div>
	<div class="ec_admin_wizard_input_row_input">Default is U.S. English - <a href="admin.php?page=wp-easycart-settings&subpage=language-editor" target="_blank">CLICK TO MANAGE LANGUAGE(S)</a></div>
</div>
<div class="ec_admin_wizard_input_row">
	<div class="ec_admin_wizard_input_row_title">Will you be charging sales tax?</div>
	<div class="ec_admin_wizard_input_row_input"><input type="checkbox" name="sales_tax" id="wp_easycart_sales_tax" value="1" onchange="wp_easycart_update_wizard_update_tax( );" /> Yes, I will be charging sales tax</div>
</div>
<div id="wp_easycart_wizard_tax_info" style="display:none;">
	<div class="ec_admin_wizard_input_row" id="wp_easycart_wizard_taxes">
		<p>The following tax rates will be imported automatically for you. You can read more about taxes in <a href="http://docs.wpeasycart.com/wp-easycart-administrative-console-guide/?section=taxes" target="_blank">our documentation</a></p>
	</div>
    <table class="wp_easycart_wizard_tax_table">
    	<thead>
        	<tr>
            	<td>Country</td>
            	<td>State</td>
            	<td>Rate (%)</td>
            	<td>Name</td>
            </tr>
        </thead>
        <tbody>
	<?php foreach( $locales as $locale ){ ?>
        <?php foreach( $locale['tax_rates'] as $tax_rates ){ ?>
        	<?php for( $i=0; $i<count( $tax_rates ); $i++ ){ ?>
    <tr class="wp_easycart_wizard_tax_row wp_easycart_wizard_tax_<?php echo $tax_rates[$i]['country']; ?><?php if( isset( $states[$tax_rates[$i]['country']] ) ){ ?>_<?php echo $tax_rates[$i]['state']; ?><?php }?>">
    	<td><?php echo $tax_rates[$i]['country']; ?></td>
        <td><?php echo $tax_rates[$i]['state']; ?></td>
        <td><?php echo $tax_rates[$i]['rate']; ?></td>
        <td><?php echo $tax_rates[$i]['name']; ?></td>
   	</tr>
	    	<?php }?>
	    <?php }?>
    <?php }?>
    	</tbody>
    </table>
</div>
<div class="ec_admin_wizard_button_bar">
	<a href="admin.php?page=wp-easycart-settings&ec_admin_form_action=skip-wizard" class="ec_admin_wizard_quit_button">Skip Setup Wizard</a>
    <a href="admin.php?page=wp-easycart-products&subpage=products">Setup Later</a>
    <input type="submit" class="ec_admin_wizard_next_button" value="Save &amp; Continue" />
</div>